### ISSUE TITLE
Supported Python Versions

### ISSUE THREAD

**Issue by ghost** [bartdegoede/python-searchengine#6]
What are the supported python versions?

I saw an [f-string](https://github.com/bartdegoede/python-searchengine/blob/9a0cc7601698a3ab9b6cf1dab278f97f7279003c/run.py#L26), so does that mean python 3.6 is the minimum supported version?

**Comment by bartdegoede** [comment]
Yeah, that would be a safe assumption. I've only really "tested" on 3.8, because this repository was intended to accompany the blog post for illustrative reasons :-)

**Comment by ghost** [comment]
> Yeah, that would be a safe assumption. I've only really "tested" on 3.8, because this repository was intended to accompany the blog post for illustrative reasons :-)

It is a great blog post.
___
I have tried the following versions:

* 2.7 obviously failed.
* 3.5 failed due to the f-strings, type annotations, and dataclasses.
* 3.6 failed due to the dataclasses.
* 3.7 worked.
* 3.8 worked.
* 3.9 worked.
